name: Build PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".github/workflows/build-pr.yml"
      - "docs/**"
      - "examples/**"
      - "libs/**"
      - "src/**"
      - "tests/**"
      - "*.sln"
      - "Directory.Build.props"

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  build-commit:
    name: "Build PR #${{ github.event.pull_request.number }}"
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Build Project
        run: dotnet build -m:1 # -m1 is needed due to https://github.com/dotnet/sdk/issues/2902
      - name: Package Project
        run: dotnet pack --include-symbols --include-source -o build -p:PullRequest="${{ github.event.pull_request.number }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WumpWump.Net-PR-${{ github.event.pull_request.number }}
          path: ./build/*
  test-commit:
    name: Test Commit
    runs-on: ubuntu-latest
    needs: build-commit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive
            fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Test Project
        run: dotnet test -m:1